modLoader = "javafml"
loaderVersion = "[32,)"
license = "All Rights Reserved"

[[mods]]
modId="wargame"
version="0.0.1"
displayName="Wargame Minecraft"
updateJSONURL=""
displayURL=""
authors="zmjlucas"
description='''
'''

[[dependencies.wargame]]
modId="forge"
mandatory=true
versionRange="[32,)"
ordering="NONE"
side="BOTH"
[[dependencies.wargame]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3,1.17)"
ordering="NONE"
side="BOTH"